project_name: scrawn

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: scrawn
    main: .
    binary: scrawn
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/ScrawnDotDev/scrawn-cli/internal/app.Version={{ .Version }}

archives:
  - id: default
    builds:
      - scrawn
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
